// Generated by scripts/media-versions.mjs. Do not edit by hand.
export const mediaVersions: Record<string, string> = {
  driftwood: "5581b0ddc4",
  "fuku-coffee": "5036d6c419",
  homestead: "d8cc6a7e24",
  nocturne: "5861cc6f1c",
  scentu: "a68705f50c",
  verum: "3f684beeb1"
};
